name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.10.0
          security-enabled: false

      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          cli: 1.11.1.1182

      - name: Test
        run: clojure -X:test qbits.spandex.test-runner/run




